# Spring Boot Settings
spring.application.name=Kraken-C2
spring.shell.interactive.enabled=true
spring.shell.script.enabled=true

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=12345678

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#API Keys
security.jwt.security-key=6b4a8f8b5c9b8e2a4f7e6c1d3dcb4a12a2f839758376e59a4c8e917f358239a1
api.key=my-secret-key
api.GO.key=my-very-secret-key

#Logging Files
logging.GOContact=/app/Logs/GOContact.txt

#Debug
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.root=INFO

server.port=9090

#Apps paths
app.kraken.terminal.path=/app
app.kraken.file-upload.upload-dir=/app/upload-dir
app.kraken.file-upload.log-file=/app/Logs/DiscoveredFiles.txt
